openapi: 3.2.0
info:
  title: SpringServe UI Creatives Filepaths API
  version: 1.0.0
  description: '> **_NOTE:_** This document covers the v1 API (`/api/v1`).'
security:
- api_key: []
- bearer_token: []
tags:
- name: Creatives Filepaths
paths:
  /api/v1/filepath_creatives:
    get:
      tags:
      - Creatives Filepaths
      summary: Index
      parameters:
      - $ref: ref/params.yaml#/components/parameters/pageParam
      - $ref: ref/params.yaml#/components/parameters/perParam
      - $ref: ref/params.yaml#/components/parameters/sortParam
      - $ref: ref/params.yaml#/components/parameters/searchParam
      - $ref: ref/params.yaml#/components/parameters/filterParams
      - $ref: ref/params.yaml#/components/parameters/includeParam
      - $ref: ref/params.yaml#/components/parameters/idsParam
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FilepathCreativeIndexResponse'
      operationId: filepath_creatives_get
    post:
      tags:
      - Creatives Filepaths
      summary: Create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FilepathCreativeCreateData'
            examples:
              create_simple:
                $ref: '#/components/examples/filepath_creative_create_simple'
              create_full:
                $ref: '#/components/examples/filepath_creative_create_full'
        required: true
      responses:
        '201':
          description: Successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FilepathCreativeResponse'
      operationId: filepath_creatives_post
  /api/v1/filepath_creatives/{id}:
    get:
      tags:
      - Creatives Filepaths
      summary: Show
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - $ref: ref/params.yaml#/components/parameters/includeParam
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FilepathCreativeResponse'
      operationId: filepath_creatives_id_get
    patch:
      tags:
      - Creatives Filepaths
      summary: Update
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - $ref: ref/params.yaml#/components/parameters/includeParam
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FilepathCreativeUpdateData'
            examples:
              update_simple:
                $ref: '#/components/examples/filepath_creative_update_simple'
              update_full:
                $ref: '#/components/examples/filepath_creative_update_full'
        required: false
      responses:
        '200':
          description: Successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FilepathCreativeResponse'
      operationId: filepath_creatives_id_patch
    delete:
      tags:
      - Creatives Filepaths
      summary: Delete
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: No content
        '422':
          $ref: ref/errors.yaml#/components/responses/validationError
      operationId: filepath_creatives_id_delete
components:
  schemas:
    FilepathCreativeBaseProperties:
      allOf:
      - type: object
        properties:
          name:
            type: string
          is_active:
            type: boolean
            default: true
          filepath_value:
            type: string
          duration_seconds:
            type: number
          clickable:
            type: boolean
          code:
            type:
            - string
            - 'null'
          secondary_code:
            type:
            - string
            - 'null'
          line_item_demand_tag_ids:
            type: array
            items:
              type: number
          iab_tier_1_category_codes:
            type: array
            items:
              type: string
          iab_tier_2_category_codes:
            type: array
            items:
              type: string
          postal_codes:
            type: array
            items:
              type: string
          postal_code_list_ids:
            type: array
            items:
              type: number
          postal_code_source:
            type: string
          postal_code_white_list:
            type: string
          key_value_targeting:
            type: boolean
          targeted_macros_enabled:
            type: boolean
          all_user_agent_devices:
            type: boolean
          all_user_agent_operating_systems:
            type: boolean
          all_user_agent_browsers:
            type: boolean
          all_user_agent_brands:
            type: boolean
          budget_timezone:
            type: string
          budgets:
            type: array
            items:
              type: object
          day_parting:
            type:
            - array
            - 'null'
            items:
              type: array
              items:
                type: boolean
          day_parting_users_timezone:
            type: boolean
          advertiser_domain:
            type:
            - string
            - 'null'
          creative_landing_page_url:
            type:
            - string
            - 'null'
      - $ref: ref/concerns/tag_pixels.yaml#/components/schemas/TagPixels
      - $ref: ref/concerns/country_codes.yaml#/components/schemas/CountryCodes
      - $ref: ref/concerns/state_codes.yaml#/components/schemas/StateCodes
      - $ref: ref/concerns/metro_area_codes.yaml#/components/schemas/MetroAreaCodes
      - $ref: ref/concerns/city_codes.yaml#/components/schemas/CityCodes
      - $ref: ref/concerns/frequency_caps.yaml#/components/schemas/FrequencyCaps
      - $ref: ref/concerns/demand_key_value.yaml#/components/schemas/DemandKeyValue
      - $ref: ref/concerns/targeted_macro.yaml#/components/schemas/TargetedMacro
      - $ref: ref/concerns/user_agent.yaml#/components/schemas/UserAgent
      - $ref: ref/concerns/flight_dates.yaml#/components/schemas/FlightDates
    FilepathCreativeResponse:
      allOf:
      - $ref: '#/components/schemas/FilepathCreativeBaseProperties'
      - type: object
        properties:
          id:
            type: integer
          account_id:
            type: integer
          demand_partner_id:
            type: integer
          creative_format:
            type: string
          type:
            type: string
          creative_landing_page_url:
            type:
            - string
            - 'null'
          netflix_pre_approval_enabled:
            type: boolean
          netflix_approval_status:
            type:
            - string
            - 'null'
          netflix_deal_ids:
            type: array
            items:
              type: string
      - $ref: ref/concerns/timestamps.yaml#/components/schemas/Timestamps
    FilepathCreativeCreateData:
      allOf:
      - $ref: '#/components/schemas/FilepathCreativeBaseProperties'
      - type: object
        required:
        - demand_partner_id
        - duration_seconds
        properties:
          demand_partner_id:
            type: number
    FilepathCreativeUpdateData:
      $ref: '#/components/schemas/FilepathCreativeBaseProperties'
    FilepathCreativeIndexResponse:
      allOf:
      - $ref: ref/params.yaml#/components/schemas/ParamsResponse
      - type: object
        properties:
          results:
            type: array
            items:
              $ref: '#/components/schemas/FilepathCreativeResponse'
  examples:
    filepath_creative_create_simple:
      summary: Simple
      value:
        name: Filepath Creative Name
        demand_partner_id: 1
        filepath_value: /path/to/creative.mp4
        duration_seconds: 1
    filepath_creative_create_full:
      summary: Full
      value:
        name: Filepath Creative Name
        demand_partner_id: 1
        filepath_value: /path/to/creative.mp4
        duration_seconds: 1
        clickable: false
        creative_landing_page_url: https://www.example.com
        advertiser_domain: example.com
        code: FP01
        secondary_code: FP01-SEC
        is_active: true
        iab_tier_1_category_codes:
        - IAB1
        iab_tier_2_category_codes:
        - IAB1-1
        line_item_demand_tag_ids:
        - 1
        country_codes:
        - US
        country_source: list
        country_list_ids:
        - 1
        country_white_list: whitelist
        state_codes:
        - NY
        state_source: list
        state_list_ids:
        - 1
        state_white_list: whitelist
        city_codes:
        - '1'
        city_source: list
        city_list_ids:
        - 1
        city_white_list: whitelist
        metro_area_codes:
        - 2001
        metro_area_source: list
        metro_area_list_ids:
        - 1
        metro_area_white_list: whitelist
        postal_codes:
        - '10001'
        postal_code_source: list
        postal_code_list_ids:
        - 1
        postal_code_white_list: whitelist
        key_value_targeting: false
        targeted_macros_enabled: false
        all_user_agent_devices: true
        all_user_agent_operating_systems: true
        all_user_agent_browsers: true
        all_user_agent_brands: true
        budget_timezone: America/New_York
        budgets:
        - budget_period: day
          budget_metric: impressions
          budget_value: 1
          budget_pacing: smooth
        start_date: '2026-01-01'
        end_date: '2026-12-31'
        flight_dates_timezone: America/New_York
        day_parting: null
        day_parting_users_timezone: false
        tag_pixels:
        - pixel_type: AdImpression
          pixel_url: https://pixel.example.com/imp
          pixel_format: image
    filepath_creative_update_full:
      summary: Full
      value:
        name: Filepath Creative Name
        filepath_value: /path/to/creative-v2.mp4
        duration_seconds: 1
        clickable: false
        creative_landing_page_url: https://www.example.com
        advertiser_domain: example.com
        code: FP01
        secondary_code: FP01-SEC
        is_active: true
        iab_tier_1_category_codes:
        - IAB1
        iab_tier_2_category_codes:
        - IAB1-1
        line_item_demand_tag_ids:
        - 1
        country_codes:
        - US
        country_source: list
        country_list_ids:
        - 1
        country_white_list: whitelist
        state_codes:
        - NY
        state_source: list
        state_list_ids:
        - 1
        state_white_list: whitelist
        city_codes:
        - '1'
        city_source: list
        city_list_ids:
        - 1
        city_white_list: whitelist
        metro_area_codes:
        - 2001
        metro_area_source: list
        metro_area_list_ids:
        - 1
        metro_area_white_list: whitelist
        postal_codes:
        - '10001'
        postal_code_source: list
        postal_code_list_ids:
        - 1
        postal_code_white_list: whitelist
        key_value_targeting: false
        targeted_macros_enabled: false
        all_user_agent_devices: true
        all_user_agent_operating_systems: true
        all_user_agent_browsers: true
        all_user_agent_brands: true
        budget_timezone: America/New_York
        budgets:
        - budget_period: day
          budget_metric: impressions
          budget_value: 1
          budget_pacing: smooth
        start_date: '2026-01-01'
        end_date: '2026-12-31'
        flight_dates_timezone: America/New_York
        day_parting: null
        day_parting_users_timezone: false
        tag_pixels:
        - pixel_type: AdImpression
          pixel_url: https://pixel.example.com/imp
          pixel_format: image
    filepath_creative_update_simple:
      summary: Simple
      value:
        name: Filepath Creative Name
        is_active: true
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: Authorization
      description: SpringServe authorization token based authentication.
    bearer_token:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: SpringServe authorization bearer token based authentication.  This key is included in the response from the /api/v0/auth and /api/v1/auth endpoints.  This key will be automatically set if you run the example for /api/v0/auth or /api/v1/auth
