openapi: 3.2.0
info:
  title: SpringServe UI API (V0) Keys API
  version: 0.1.0
  description: '> **_NOTE:_** This document covers the v0 API (`/api/v0`).'
security:
- api_key: []
- bearer_token: []
tags:
- name: Keys
paths:
  /api/v0/keys:
    get:
      summary: Index
      parameters:
      - $ref: ref/params.yaml#/components/parameters/pageParam
      - $ref: ref/params.yaml#/components/parameters/perParam
      - $ref: ref/params.yaml#/components/parameters/idsParam
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: ref/schemas.yaml#/components/schemas/ListResponse
      tags:
      - Keys
      operationId: keys_get
    post:
      summary: Create
      requestBody:
        content:
          application/json:
            schema:
              type: object
            examples:
              key_create_simple:
                $ref: '#/components/examples/key_create_simple'
              key_create_full:
                $ref: '#/components/examples/key_create_full'
        required: true
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Keys
      operationId: keys_post
  /api/v0/keys/{id}:
    get:
      summary: Show
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Keys
      operationId: keys_id_get
    put:
      summary: Update
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
            examples:
              key_update_simple:
                $ref: '#/components/examples/key_update_simple'
              key_update_full:
                $ref: '#/components/examples/key_update_full'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Keys
      operationId: keys_id_put
    delete:
      summary: Destroy
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: No content
      tags:
      - Keys
      operationId: keys_id_delete
  /api/v0/keys/{key_id}/values:
    get:
      summary: Index
      parameters:
      - name: key_id
        in: path
        required: true
        schema:
          type: string
      - $ref: ref/params.yaml#/components/parameters/pageParam
      - $ref: ref/params.yaml#/components/parameters/perParam
      - $ref: ref/params.yaml#/components/parameters/idsParam
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: ref/schemas.yaml#/components/schemas/ListResponse
      tags:
      - Keys
      operationId: keys_key_id_values_get
    post:
      summary: Create
      parameters:
      - name: key_id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
            examples:
              key_value_create_simple:
                $ref: '#/components/examples/key_value_create_simple'
              key_value_create_full:
                $ref: '#/components/examples/key_value_create_full'
        required: true
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Keys
      operationId: keys_key_id_values_post
  /api/v0/keys/{key_id}/values/{value_id}:
    get:
      summary: Show
      parameters:
      - name: key_id
        in: path
        required: true
        schema:
          type: string
      - name: value_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Keys
      operationId: keys_key_id_values_value_id_get
    put:
      summary: Update
      parameters:
      - name: key_id
        in: path
        required: true
        schema:
          type: string
      - name: value_id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
            examples:
              key_value_update_simple:
                $ref: '#/components/examples/key_value_update_simple'
              key_value_update_full:
                $ref: '#/components/examples/key_value_update_full'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Keys
      operationId: keys_key_id_values_value_id_put
    patch:
      summary: Update
      parameters:
      - name: key_id
        in: path
        required: true
        schema:
          type: string
      - name: value_id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
            examples:
              key_value_update_simple:
                $ref: '#/components/examples/key_value_update_simple'
              key_value_update_full:
                $ref: '#/components/examples/key_value_update_full'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Keys
      operationId: keys_key_id_values_value_id_patch
    delete:
      summary: Destroy
      parameters:
      - name: key_id
        in: path
        required: true
        schema:
          type: string
      - name: value_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: No content
      tags:
      - Keys
      operationId: keys_key_id_values_value_id_delete
components:
  examples:
    key_value_update_full:
      summary: Full
      value:
        name: Key Name
        value: updated-value
    key_value_create_full:
      summary: Full
      value:
        name: Key Name
        value: my-value
    key_create_simple:
      summary: Simple
      value:
        name: Key Name
        key: my-custom-key
        definition_type: free
    key_create_full:
      summary: Full
      value:
        name: Key Name
        key: my-custom-key
        definition_type: predefined
        description: Key description
        log_level_reporting_only: false
        supply_client_reporting_enabled: true
        demand_client_reporting_enabled: true
        key_sharing_enabled: false
    key_update_simple:
      summary: Simple
      value:
        name: Key Name
    key_value_create_simple:
      summary: Simple
      value:
        name: Key Name
        value: my-value
    key_value_update_simple:
      summary: Simple
      value:
        name: Key Name
    key_update_full:
      summary: Full
      value:
        name: Key Name
        description: Updated key description
        log_level_reporting_only: false
        supply_client_reporting_enabled: true
        demand_client_reporting_enabled: true
        key_sharing_enabled: true
        key_sharing_other_account_ids:
        - 1
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: Authorization
      description: SpringServe authorization token based authentication.
    bearer_token:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: SpringServe authorization bearer token based authentication.  This key is included in the response from the /api/v0/auth and /api/v1/auth endpoints.  This key will be automatically set if you run the example for /api/v0/auth or /api/v1/auth
