openapi: 3.2.0
info:
  title: SpringServe UI API (V0) Connected Supply API
  version: 0.1.0
  description: '> **_NOTE:_** This document covers the v0 API (`/api/v0`).'
security:
- api_key: []
- bearer_token: []
tags:
- name: Connected Supply
paths:
  /api/v0/connected_supply:
    get:
      summary: Index
      description: 'Buying strategies (path alias: connected_supply)'
      parameters:
      - $ref: ref/params.yaml#/components/parameters/pageParam
      - $ref: ref/params.yaml#/components/parameters/perParam
      - $ref: ref/params.yaml#/components/parameters/idsParam
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: ref/schemas.yaml#/components/schemas/ListResponse
      tags:
      - Connected Supply
      operationId: connected_supply_get
    post:
      summary: Create
      requestBody:
        content:
          application/json:
            schema:
              type: object
            examples:
              simple:
                $ref: '#/components/examples/buying_strategy_create_simple'
              full:
                $ref: '#/components/examples/buying_strategy_create_full'
        required: true
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Connected Supply
      operationId: connected_supply_post
  /api/v0/connected_supply/{id}:
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
    get:
      summary: Show
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Connected Supply
      operationId: connected_supply_id_get
    put:
      summary: Update
      requestBody:
        content:
          application/json:
            schema:
              type: object
            examples:
              simple:
                $ref: '#/components/examples/buying_strategy_update_simple'
              full:
                $ref: '#/components/examples/buying_strategy_update_full'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Connected Supply
      operationId: connected_supply_id_put
  /api/v0/connected_supply/{id}/duplicate:
    get:
      summary: Duplicate
      description: Duplicate the buying strategy
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Connected Supply
      operationId: connected_supply_id_duplicate_get
components:
  examples:
    buying_strategy_update_simple:
      summary: Simple
      value:
        active: true
    buying_strategy_update_full:
      summary: Full
      value:
        name: Connected Supply Name
        active: true
        environment: desktop
        domain_targeting: true
        domain_list_ids:
        - 1
        app_name_targeting: true
        app_name_list_ids:
        - 1
        app_bundle_targeting: true
        app_bundle_list_ids:
        - 1
        ip_targeting: true
        ip_list_ids:
        - 1
        country_targeting: true
        country_source: list
        country_list_ids:
        - 1
        state_targeting: true
        state_source: list
        state_list_ids:
        - 1
        city_targeting: true
        city_source: list
        city_list_ids:
        - 1
        metro_area_targeting: true
        metro_area_source: list
        metro_area_list_ids:
        - 1
        postal_code_targeting: true
        postal_code_source: list
        postal_code_list_ids:
        - 1
        allowed_player_sizes:
        - s
        - m
        - l
        segment_targeting_enabled: false
        targeted_macros_enabled: false
        blocking_unknown_advertiser_domains: false
        pre_bid_blocking_enabled: false
        post_imp_detection_enabled: false
        budget_timezone: America/New_York
        tag_pixels:
        - pixel_type: AdImpression
          pixel_format: image
          pixel_url: https://pixel.example.com/imp
        demand_tag_priorities:
        - demand_tag_id: 1
          priority: 1
          tier: 1
    buying_strategy_create_simple:
      summary: Simple
      value:
        supply_partner_id: 1
        rate: 1.11
        rate_currency: USD
    buying_strategy_create_full:
      summary: Full
      value:
        supply_partner_id: 1
        name: Connected Supply Name
        rate: 1.11
        rate_currency: USD
        active: true
        environment: desktop
        revenue_model_type: 0
        domain_targeting: true
        domain_list_ids:
        - 1
        app_name_targeting: true
        app_name_list_ids:
        - 1
        app_bundle_targeting: true
        app_bundle_list_ids:
        - 1
        ip_targeting: true
        ip_list_ids:
        - 1
        country_targeting: true
        country_source: list
        country_list_ids:
        - 1
        state_targeting: true
        state_source: list
        state_list_ids:
        - 1
        city_targeting: true
        city_source: list
        city_list_ids:
        - 1
        metro_area_targeting: true
        metro_area_source: list
        metro_area_list_ids:
        - 1
        postal_code_targeting: true
        postal_code_source: list
        postal_code_list_ids:
        - 1
        allowed_player_sizes:
        - s
        - m
        - l
        segment_targeting_enabled: false
        targeted_macros_enabled: false
        blocking_unknown_advertiser_domains: false
        pre_bid_blocking_enabled: false
        post_imp_detection_enabled: false
        budget_timezone: America/New_York
        tag_pixels:
        - pixel_type: AdImpression
          pixel_format: image
          pixel_url: https://pixel.example.com/imp
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: Authorization
      description: SpringServe authorization token based authentication.
    bearer_token:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: SpringServe authorization bearer token based authentication.  This key is included in the response from the /api/v0/auth and /api/v1/auth endpoints.  This key will be automatically set if you run the example for /api/v0/auth or /api/v1/auth
