openapi: 3.2.0
info:
  title: SpringServe UI User Accounts API
  version: 1.0.0
  description: '> **_NOTE:_** This document covers the v1 API (`/api/v1`).'
security:
- api_key: []
- bearer_token: []
tags:
- name: User Accounts
  description: The entity that combines a User and an Account and defines the role the user plays on that account
paths:
  /api/v1/user_accounts:
    get:
      summary: Index
      description: 'For sorting in addition to regular attributes, you can also sort by `client_object_type_partner` and `client_object_type_label` which

        are whether `client_object_type=''partner''` or `client_object_type=''label''` respectively.'
      parameters:
      - $ref: ref/params.yaml#/components/parameters/pageParam
      - $ref: ref/params.yaml#/components/parameters/perParam
      - $ref: ref/params.yaml#/components/parameters/sortParam
      - $ref: ref/params.yaml#/components/parameters/searchParam
      - $ref: ref/params.yaml#/components/parameters/filterParams
      - name: partner_name
        description: filter based on supply partner or demand partner name
        in: query
        schema:
          type: string
      - name: label_name
        description: filter based on supply label or demand label name
        in: query
        schema:
          type: string
      - $ref: ref/params.yaml#/components/parameters/includeParam
      - $ref: ref/params.yaml#/components/parameters/idsParam
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - User Accounts
      operationId: user_accounts_get
    post:
      summary: Create
      requestBody:
        content:
          application/json:
            schema:
              type: object
            examples:
              simple:
                $ref: '#/components/examples/user_account_create_simple'
              full:
                $ref: '#/components/examples/user_account_create_full'
        required: true
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - User Accounts
      operationId: user_accounts_post
  /api/v1/user_accounts/{id}:
    get:
      summary: Show
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - $ref: ref/params.yaml#/components/parameters/includeParam
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - User Accounts
      operationId: user_accounts_id_get
    patch:
      summary: Update
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
            examples:
              simple:
                $ref: '#/components/examples/user_account_update_simple'
              full:
                $ref: '#/components/examples/user_account_update_full'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - User Accounts
      operationId: user_accounts_id_patch
    delete:
      summary: Delete
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: No content
      tags:
      - User Accounts
      operationId: user_accounts_id_delete
  /api/v1/user_accounts/bulk_update:
    post:
      summary: Bulk Update one or more attributes
      requestBody:
        content:
          application/json:
            schema:
              type: object
            examples:
              single:
                $ref: '#/components/examples/user_account_bulk_update_single'
              multiple:
                $ref: '#/components/examples/user_account_bulk_update_multiple'
        required: true
      responses:
        '200':
          description: Bulk update completed
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Status message describing the bulk update results
                examples:
                - message: 'Successfully updated 2 User Accounts: 16, 17'
      tags:
      - User Accounts
      operationId: user_accounts_bulk_update_same_attributes_post
  /api/v1/user_accounts/meta:
    get:
      summary: Meta
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - User Accounts
      operationId: user_accounts_meta_get
  /api/v1/user_accounts/permissions:
    get:
      summary: Permissions Collection
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - User Accounts
      operationId: user_accounts_permissions_get
  /api/v1/user_accounts/{id}/permissions:
    get:
      summary: Permissions Member
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - User Accounts
      operationId: user_accounts_id_permissions_get
components:
  examples:
    user_account_update_simple:
      summary: Simple
      value:
        is_active: true
    user_account_bulk_update_single:
      summary: Single
      value:
        is_active: true
        object_ids:
        - 1
    user_account_bulk_update_multiple:
      summary: Multiple
      value:
        is_active: false
        object_ids:
        - 1
        - 2
    user_account_create_simple:
      summary: Simple
      value:
        email: user@example.com
        role: analytics
    user_account_update_full:
      summary: Full
      value:
        role: ad_ops
        client_object_type: partner
        supply_partner_ids:
        - 1
        demand_partner_ids:
        - 1
        supply_label_ids:
        - 1
        demand_label_ids:
        - 1
        read_marketplace_ids:
        - 1
        write_marketplace_ids:
        - 1
        account_contact: false
        high_volume_user: false
        is_active: true
    user_account_create_full:
      summary: Full
      value:
        email: user@example.com
        role: supply_client
        client_object_type: partner
        supply_partner_ids:
        - 1
        demand_partner_ids: []
        supply_label_ids: []
        demand_label_ids: []
        read_marketplace_ids: []
        write_marketplace_ids: []
        account_contact: false
        high_volume_user: false
        is_active: true
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: Authorization
      description: SpringServe authorization token based authentication.
    bearer_token:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: SpringServe authorization bearer token based authentication.  This key is included in the response from the /api/v0/auth and /api/v1/auth endpoints.  This key will be automatically set if you run the example for /api/v0/auth or /api/v1/auth
