openapi: 3.2.0
info:
  title: SpringServe UI API (V0) Operative API
  version: 0.1.0
  description: '> **_NOTE:_** This document covers the v0 API (`/api/v0`).'
security:
- api_key: []
- bearer_token: []
tags:
- name: Operative
paths:
  /api/v0/operative/advertisers:
    post:
      summary: Create Operative Advertiser
      description: Create an advertiser in Operative integration
      requestBody:
        content:
          application/json:
            schema:
              type: object
            examples:
              operative_advertiser_create_simple:
                $ref: '#/components/examples/operative_advertiser_create_simple'
              operative_advertiser_create_full:
                $ref: '#/components/examples/operative_advertiser_create_full'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Operative
      operationId: operative_advertisers_post
  /api/v0/operative/orders:
    post:
      summary: Create Operative Order
      description: Create an order in Operative integration
      requestBody:
        content:
          application/json:
            schema:
              type: object
            examples:
              operative_order_create_simple:
                $ref: '#/components/examples/operative_order_create_simple'
              operative_order_create_full:
                $ref: '#/components/examples/operative_order_create_full'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Operative
      operationId: operative_orders_post
    put:
      summary: Update Operative Order
      description: Update an order in Operative integration
      requestBody:
        content:
          application/json:
            schema:
              type: object
            examples:
              operative_order_update_simple:
                $ref: '#/components/examples/operative_order_update_simple'
              operative_order_update_full:
                $ref: '#/components/examples/operative_order_update_full'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      tags:
      - Operative
      operationId: operative_orders_put
components:
  examples:
    operative_order_update_simple:
      summary: Simple
      value:
        orderId: '1'
        lineitems:
        - lineitemId: '1'
          name: Operative Line Item Name
    operative_order_create_simple:
      summary: Simple
      value:
        sourceOrderId: '1'
        name: Operative Order Name
        advertiserId: '1'
    operative_order_update_full:
      summary: Full
      value:
        orderId: '1'
        lineitems:
        - lineitemId: '1'
          sourceLineitemId: '1'
          name: Operative Line Item Name
          quantity: 1
          costType: CPM
          unitCost: 1.11
          timeZone: America/New_York
          startDate: '2026-01-01'
          endDate: '2026-12-31'
          targets:
          - targetName: geo
            targetValues:
            - US
    operative_advertiser_create_full:
      summary: Full
      value:
        sourceAdvertiserId: '1'
        name: Operative Advertiser Name
    operative_advertiser_create_simple:
      summary: Simple
      value:
        sourceAdvertiserId: '1'
        name: Operative Advertiser Name
    operative_order_create_full:
      summary: Full
      value:
        sourceOrderId: '1'
        name: Operative Order Name
        advertiserId: '1'
        startDate: '2026-01-01'
        endDate: '2026-12-31'
        lineitems:
        - lineitemId: '1'
          sourceLineitemId: '1'
          name: Operative Line Item Name
          quantity: 1
          costType: CPM
          unitCost: 1.11
          timeZone: America/New_York
          startDate: '2026-01-01'
          endDate: '2026-12-31'
          targets:
          - targetName: geo
            targetValues:
            - US
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: Authorization
      description: SpringServe authorization token based authentication.
    bearer_token:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: SpringServe authorization bearer token based authentication.  This key is included in the response from the /api/v0/auth and /api/v1/auth endpoints.  This key will be automatically set if you run the example for /api/v0/auth or /api/v1/auth
